# Generated by Django 3.1.4 on 2021-01-16 09:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee/', verbose_name='Image')),
                ('price', models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.cart')),
                ('drink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.drink')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название кофейни')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe/', verbose_name='Image')),
                ('drinks', models.ManyToManyField(to='coffeeshop.Drink')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='coffeeshop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafe_name', to='coffeeshop.coffeeshop'),
        ),
    ]
