# Generated by Django 3.1.4 on 2021-01-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.cart'),
        ),
    ]
