# Generated by Django 3.1.4 on 2021-01-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0003_auto_20210117_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkorder',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.drink'),
        ),
    ]
